FROM node:lts AS runtime
WORKDIR /app

ARG SANITY_PROJECT_ID
ENV SANITY_PROJECT_ID $SANITY_PROJECT_ID

ARG SANITY_DATASET
ENV SANITY_DATASET $SANITY_DATASET

COPY . .

RUN npm install
RUN npm install -g pm2
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=8080
EXPOSE 8080
CMD ["pm2-runtime", "pm2.json"]
