export const GLOBAL_PERSIST_RESOURCES_CONTAINER =
    "GLOBAL_PERSIST_RESOURCES_CONTAINER";
export const MAIN_BLOCK_WITH_SIDEBAR_SIDE_SWITCH_SMALL_SCREEN =
    "MAIN_BLOCK_WITH_SIDEBAR_SIDE_SWITCH_SMALL_SCREEN";
export const VIDEO_LIST_PAGE_CATEGORY_SWITCH_SMALL_SCREEN =
    "VIDEO_LIST_PAGE_CATEGORY_SWITCH_SMALL_SCREEN";
